/*
 * frmRubros.java
 *
 * Created on 1 de noviembre de 2007, 09:10 PM
 */
package bean;

import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import java.awt.Container;
import java.math.BigDecimal;
import jcinform.persistencia.Empleados;
import jcinform.persistencia.Periodos;
import jcinform.persistencia.Rubros;
import jcinform.procesos.Administrador;

/**
 *
 * @author Francisco
 */
public class frmRubros extends javax.swing.JInternalFrame {

    public boolean grabar = false;
    public boolean modificar = false;
       public Periodos periodoActual;
    public Empleados empleadoActual;
    Administrador adm;

    /**
     * Creates new form frmRubros
     */
    public frmRubros() {
        initComponents();
        ancho();
       
    }

    public frmRubros(Administrador adm1) {
    
        adm = adm1;
        this.initComponents();
        listar();
     
        lblCodigo.setVisible(false);
        codigoRubro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRubros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        chkEscredito = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        valor = new javax.swing.JFormattedTextField();
        codigoRubro = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codigoContable = new javax.swing.JFormattedTextField();
        unidadContable = new javax.swing.JFormattedTextField();
        lblCodigo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 246, 255));
        setTitle("Creación de Rubros");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rubros.gif"))); // NOI18N
        getContentPane().setLayout(null);

        txtNombre.setEditable(false);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(140, 50, 340, 25);

        tableRubros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Valor", "CRÉDITO", "Cod.Contable", "Uni.Contable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRubros.setSelectionBackground(new java.awt.Color(236, 246, 255));
        tableRubros.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableRubros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRubrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRubros);
        tableRubros.getColumnModel().getColumn(0).setPreferredWidth(10);
        tableRubros.getColumnModel().getColumn(1).setMinWidth(100);
        tableRubros.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableRubros.getColumnModel().getColumn(1).setMaxWidth(200);
        tableRubros.getColumnModel().getColumn(2).setResizable(false);
        tableRubros.getColumnModel().getColumn(3).setResizable(false);
        tableRubros.getColumnModel().getColumn(4).setResizable(false);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 490, 210);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre de Rubro:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 50, 110, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.gif"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo);
        btnNuevo.setBounds(10, 10, 105, 30);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modificar.gif"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar);
        btnModificar.setBounds(120, 10, 110, 30);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.gif"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(350, 10, 105, 30);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.gif"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(240, 10, 105, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 150, 480, 50);

        chkEscredito.setBackground(new java.awt.Color(236, 246, 255));
        chkEscredito.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkEscredito.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkEscredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEscreditoActionPerformed(evt);
            }
        });
        getContentPane().add(chkEscredito);
        chkEscredito.setBounds(370, 80, 80, 30);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Unidad contable:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 110, 110, 30);

        valor.setEditable(false);
        getContentPane().add(valor);
        valor.setBounds(140, 80, 110, 25);

        codigoRubro.setEditable(false);
        getContentPane().add(codigoRubro);
        codigoRubro.setBounds(140, 140, 60, 10);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Valor:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 80, 120, 20);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Es el Crédito:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 80, 100, 30);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Código contable:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 110, 120, 20);

        codigoContable.setEditable(false);
        getContentPane().add(codigoContable);
        codigoContable.setBounds(140, 110, 110, 25);

        unidadContable.setEditable(false);
        getContentPane().add(unidadContable);
        unidadContable.setBounds(370, 110, 110, 25);

        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodigo.setText("Código:");
        getContentPane().add(lblCodigo);
        lblCodigo.setBounds(50, 140, 80, 10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Crear, Actualizar, Modificar Rubros.......");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 20, 210, 13);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Catálogo de Rubros ..::..");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 0, 200, 15);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoInicio.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 520, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
// TODO add your handling code here:
         if (grabar == true) {
               grabar = false;
            modificar = false;
            this.valor.setEditable(false);
            this.btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar.png")));
            this.btnNuevo.setLabel("Nuevo");
            this.btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modificar.gif")));
            this.btnModificar.setLabel("Modificar");
            this.txtNombre.setEditable(false);
         }
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
// TODO add your handling code here:

        if (grabar == false) {
            this.txtNombre.setEditable(true);
            this.unidadContable.setEditable(true);
            this.codigoContable.setEditable(true);
            
            this.txtNombre.requestFocusInWindow();
            this.txtNombre.setText("");
            this.codigoRubro.setText("");
            this.valor.setText("");
            this.codigoContable.setText("");
            this.unidadContable.setText("");
            this.valor.setEditable(true);
            this.btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guardar.png")));
            this.btnNuevo.setLabel("Guardar");
            this.btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png")));
            this.btnModificar.setLabel("Cancelar");

            grabar = true;
            modificar = false;
        } else if (grabar == true) {
            if(chkEscredito.isSelected()){
            adm.ejecutaSql("Update Rubros set eselcredito = false"); 
            }
            Rubros rub = new Rubros();
            rub.setNombre(txtNombre.getText());
            rub.setEselcredito((chkEscredito.isSelected()));
            rub.setValor(new BigDecimal(valor.getText()));
            rub.setCodigoContable(codigoContable.getText());
            rub.setUnidadContable(unidadContable.getText());
            if (codigoRubro.getText().isEmpty()) {
                rub.setIdRubros(adm.getNuevaClave("Rubros", "idRubros"));
                adm.guardar(rub);
            } else {
                rub.setIdRubros(new Integer(codigoRubro.getText()));
                adm.actualizar(rub);
            }


            listar();
            this.valor.setEditable(false);
            this.btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.gif")));
            this.btnNuevo.setLabel("Nuevo");
            this.btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modificar.gif")));
            this.btnModificar.setLabel("Modificar");
            grabar = false;
            modificar = false;
            this.txtNombre.setEditable(false);

        }

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
// TODO add your handling code here:

        Rubros rub = new Rubros();

        rub.setIdRubros(Integer.parseInt(codigoRubro.getText()));
        adm.eliminarObjeto(Rubros.class, rub.getIdRubros());
        listar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
// TODO add your handling code here:
        if (grabar == false) {
            if(codigoRubro.getText().isEmpty()){
                return;
            }
            this.txtNombre.setEditable(true);
            this.unidadContable.setEditable(true);
            this.codigoContable.setEditable(true);
            this.txtNombre.requestFocusInWindow();
            this.valor.setEditable(true);
            this.btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guardar.png")));
            this.btnNuevo.setLabel("Guardar");
            this.btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png")));
            this.btnModificar.setLabel("Cancelar");
            modificar = true;
            grabar = true;
        } else {
            grabar = false;
            modificar = false;
            this.valor.setEditable(false);
            this.btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar.png")));
            this.btnNuevo.setLabel("Nuevo");
            this.btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modificar.gif")));
            this.btnModificar.setLabel("Modificar");
            this.txtNombre.setEditable(false);
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void tableRubrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRubrosMouseClicked
// TODO add your handling code here:
        int fila = tableRubros.getSelectedRow();
        this.codigoRubro.setText(Integer.parseInt(tableRubros.getValueAt(fila, 0).toString()) + "");
        this.txtNombre.setText((String) this.tableRubros.getValueAt(fila, 1));
        this.valor.setText(((BigDecimal) tableRubros.getValueAt(fila, 2)) + "");
        boolean val = new Boolean(tableRubros.getValueAt(fila, 3).toString());
        this.chkEscredito.setSelected(Boolean.valueOf(val));
        this.codigoContable.setText((String) this.tableRubros.getValueAt(fila, 4));
        this.unidadContable.setText((String) this.tableRubros.getValueAt(fila, 5));

        //boolean val2 = new Boolean(.toString());
//        this.chkEstado.setSelected((Boolean)tableRubros.getValueAt(fila,3));
    }//GEN-LAST:event_tableRubrosMouseClicked

    private void chkEscreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEscreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEscreditoActionPerformed

    public void listar() {

        List lista = adm.query("Select o from Rubros as o ");
        DefaultTableModel dtm = (DefaultTableModel) tableRubros.getModel();
        dtm.getDataVector().removeAllElements();
        for (Iterator it = lista.iterator(); it.hasNext();) {
            Rubros elem = (Rubros) it.next();
            Object obj[] = new Object[7];
            obj[0] = elem.getIdRubros();
            obj[1] = elem.getNombre();
            obj[2] = elem.getValor();
            obj[3] = elem.getEselcredito();
            obj[4] = elem.getCodigoContable();
            obj[5] = elem.getUnidadContable();
            dtm.addRow(obj);
        }
        tableRubros.setModel(dtm);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkEscredito;
    private javax.swing.JFormattedTextField codigoContable;
    private javax.swing.JFormattedTextField codigoRubro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTable tableRubros;
    private javax.swing.JFormattedTextField txtNombre;
    private javax.swing.JFormattedTextField unidadContable;
    private javax.swing.JFormattedTextField valor;
    // End of variables declaration//GEN-END:variables

    public void ancho() {
        TableColumn column;
        for (int i = 0; i < 3; i++) {
            column = this.tableRubros.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(50);
            }
            if (i == 1) {
                column.setPreferredWidth(350);
            }
            if (i == 2) {
                column.setPreferredWidth(100);
            }



        }

    }

    public Periodos getPeriodoActual() {
        return periodoActual;
    }

    public void setPeriodoActual(Periodos periodoActual) {
        this.periodoActual = periodoActual;
    }

    public Empleados getEmpleadoActual() {
        return empleadoActual;
    }

    public void setEmpleadoActual(Empleados empleadoActual) {
        this.empleadoActual = empleadoActual;
    }
    
    
}
