/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tomarImage.java
 *
 * Created on 16/07/2011, 09:17:14 PM
 */
package camaraIP;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Geovanny Jadan
 */
public class tomarImage extends javax.swing.JFrame {

    /** Creates new form tomarImage */
    public tomarImage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        miLabel = new javax.swing.JLabel();
        miPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ventana con Imagenes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Setear foto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        miLabel.setText("jLabel1");

        javax.swing.GroupLayout miPanelLayout = new javax.swing.GroupLayout(miPanel);
        miPanel.setLayout(miPanelLayout);
        miPanelLayout.setHorizontalGroup(
            miPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        miPanelLayout.setVerticalGroup(
            miPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        jButton3.setText("añadira a label");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(58, 58, 58)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(miLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(miPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(miPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(miLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Imagenes v = new Imagenes();
        v.setSize(300, 250);
        v.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        URL nUrl = null;

        try {
            nUrl = new URL("http://192.168.10.3/cgi-bin/viewer/video.jpg");
        } catch (MalformedURLException ex) {
            ex.printStackTrace();
        }

        //public BufferedImage image = null;
        try {
            image = ImageIO.read(nUrl);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        miPanel = new ImagePanel();
//         miPanel.paintComponents(miPanel.getGraphics());
//         miPanel.setLocation(100, 100);
//         miLabel = new JLabel(new ImageIcon( image));
//         miLabel.repaint();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        URL nUrl = null;

        try {
            nUrl = new URL("http://192.168.10.3/cgi-bin/viewer/video.jpg");
        } catch (MalformedURLException ex) {
            ex.printStackTrace();
        }

        //public BufferedImage image = null;
        try {
            image = ImageIO.read(nUrl);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        try {

            File outputfile = new File("f://miimagen.jpg");
            ImageIO.write(image, "jpg", outputfile);
            miLabel.setIcon(new ImageIcon(image));
            //JLabel picLabel = new JLabel(new ImageIcon(image));
            //add(picLabel);
//            Image image = Toolkit.getDefaultToolkit().getImage("f://miimagen.jpg");
//            //Icon icon = new ImageIcon(image);
//            ImageIcon tmpIconAux = new ImageIcon(image);
//            ImageIcon tmpIcon = new ImageIcon(tmpIconAux.getImage().getScaledInstance(700, -1, Image.SCALE_DEFAULT));
//            miLabel.setIcon(tmpIcon);


//            BufferedImage myPicture = ImageIO.read(outputfile);
//            JLabel picLabel = new JLabel(new ImageIcon( myPicture ));
//            add( picLabel );



        } catch (IOException e) {
        }


    }//GEN-LAST:event_jButton3ActionPerformed
    public void tomarFotoIp(String Carpeta) {
        URL nUrl = null;

        try {
            nUrl = new URL("http://192.168.10.3/cgi-bin/viewer/video.jpg");
        } catch (MalformedURLException ex) {
            ex.printStackTrace();
        }

        //public BufferedImage image = null;
        try {
            image = ImageIO.read(nUrl);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        try {

            File outputfile = new File(Carpeta+"");
            ImageIO.write(image, "jpg", outputfile);
            miLabel.setIcon(new ImageIcon(image));

        } catch (IOException e) {
        }

    }
    public BufferedImage image = null;
//     public void paint(Graphics g){
//         
//        
//        Graphics2D g2 = (Graphics2D)g; 
//        URL nUrl = null;
//              
//        try {
//          nUrl = new URL("http://192.168.10.3/cgi-bin/viewer/video.jpg");
//        } catch (MalformedURLException ex) {
//            ex.printStackTrace();
//        }
//        
//        //public BufferedImage image = null;
//        try {
//          image = ImageIO.read(nUrl);
//        } catch (IOException ex) {
//            ex.printStackTrace();
//       }
//        
//        setTitle("Imagen_Camara");   
//        g2.drawImage(image,100,100,this);
//        repaint();
//        
//       
//     
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new tomarImage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel miLabel;
    private javax.swing.JPanel miPanel;
    // End of variables declaration//GEN-END:variables
}
