/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 05/05/2011, 04:37:45 PM
 */
package historias.formas;

import java.awt.Color;
import java.awt.ComponentOrientation;
import javax.swing.JOptionPane;

/**
 *
 * @author Familia Jadan Cahueñ
 */
public class NewJFrame extends javax.swing.JFrame {
String diente = "";
    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        this.setSize(399, 299);
//        BotonRedondo b = new BotonRedondo("DFGSDF GSDFGSD FGSDF ", Color.BLUE, Color.red);
//        b.setContentAreaFilled(false);
//          getContentPane().add(b);
//          b.setBounds(60, 100, 73, 43);
       }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submenu = new javax.swing.JPopupMenu();
        cariada = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        diente11 = new javax.swing.JPanel();
        sup11 = new javax.swing.JButton();
        cen11 = new javax.swing.JButton();
        izq11 = new javax.swing.JButton();
        der11 = new javax.swing.JButton();
        inf11 = new javax.swing.JButton();
        per11 = new javax.swing.JButton();
        diente12 = new javax.swing.JPanel();
        sup12 = new javax.swing.JButton();
        cen12 = new javax.swing.JButton();
        izq12 = new javax.swing.JButton();
        der12 = new javax.swing.JButton();
        inf12 = new javax.swing.JButton();
        per12 = new javax.swing.JButton();

        cariada.setText("Cariada");
        cariada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariadaActionPerformed(evt);
            }
        });
        submenu.add(cariada);

        jMenuItem1.setText("Picada");
        submenu.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        diente11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "11", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        diente11.setLayout(null);

        sup11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseSup.png"))); // NOI18N
        sup11.setBorder(null);
        sup11.setBorderPainted(false);
        sup11.setContentAreaFilled(false);
        sup11.setMargin(new java.awt.Insets(1, 1, 1, 1));
        sup11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseSupS.png"))); // NOI18N
        sup11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseSupS.png"))); // NOI18N
        sup11.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseSupS.png"))); // NOI18N
        sup11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sup11MouseClicked(evt);
            }
        });
        diente11.add(sup11);
        sup11.setBounds(10, 20, 50, 15);

        cen11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseCen.png"))); // NOI18N
        cen11.setBorder(null);
        cen11.setBorderPainted(false);
        cen11.setContentAreaFilled(false);
        cen11.setMargin(new java.awt.Insets(1, 1, 1, 1));
        cen11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseCenS.png"))); // NOI18N
        cen11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseCenS.png"))); // NOI18N
        cen11.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseCenS.png"))); // NOI18N
        cen11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cen11MouseClicked(evt);
            }
        });
        diente11.add(cen11);
        cen11.setBounds(24, 34, 22, 22);

        izq11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseIzq.png"))); // NOI18N
        izq11.setBorder(null);
        izq11.setBorderPainted(false);
        izq11.setContentAreaFilled(false);
        izq11.setMargin(new java.awt.Insets(1, 1, 1, 1));
        izq11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseIzqS.png"))); // NOI18N
        izq11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseIzqS.png"))); // NOI18N
        izq11.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseIzqS.png"))); // NOI18N
        izq11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izq11MouseClicked(evt);
            }
        });
        diente11.add(izq11);
        izq11.setBounds(10, 20, 15, 50);

        der11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseDer.png"))); // NOI18N
        der11.setBorder(null);
        der11.setBorderPainted(false);
        der11.setContentAreaFilled(false);
        der11.setMargin(new java.awt.Insets(1, 1, 1, 1));
        der11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseDerS.png"))); // NOI18N
        der11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseDerS.png"))); // NOI18N
        der11.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseDerS.png"))); // NOI18N
        der11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                der11MouseClicked(evt);
            }
        });
        diente11.add(der11);
        der11.setBounds(44, 20, 15, 50);

        inf11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseInf.png"))); // NOI18N
        inf11.setBorder(null);
        inf11.setBorderPainted(false);
        inf11.setContentAreaFilled(false);
        inf11.setMargin(new java.awt.Insets(1, 1, 1, 1));
        inf11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseInfS.png"))); // NOI18N
        inf11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseInfS.png"))); // NOI18N
        inf11.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseInfS.png"))); // NOI18N
        inf11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inf11MouseClicked(evt);
            }
        });
        diente11.add(inf11);
        inf11.setBounds(10, 54, 50, 15);

        per11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/perdida.png"))); // NOI18N
        per11.setBorderPainted(false);
        per11.setContentAreaFilled(false);
        diente11.add(per11);
        per11.setBounds(10, 20, 50, 50);

        getContentPane().add(diente11);
        diente11.setBounds(30, 30, 70, 80);

        diente12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "12", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        diente12.setLayout(null);

        sup12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseSup.png"))); // NOI18N
        sup12.setBorder(null);
        sup12.setBorderPainted(false);
        sup12.setContentAreaFilled(false);
        sup12.setMargin(new java.awt.Insets(1, 1, 1, 1));
        sup12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseSupS.png"))); // NOI18N
        sup12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseSupS.png"))); // NOI18N
        sup12.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseSupS.png"))); // NOI18N
        sup12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sup12MouseClicked(evt);
            }
        });
        diente12.add(sup12);
        sup12.setBounds(10, 20, 50, 15);

        cen12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseCen.png"))); // NOI18N
        cen12.setBorder(null);
        cen12.setBorderPainted(false);
        cen12.setContentAreaFilled(false);
        cen12.setMargin(new java.awt.Insets(1, 1, 1, 1));
        cen12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseCenS.png"))); // NOI18N
        cen12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseCenS.png"))); // NOI18N
        cen12.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseCenS.png"))); // NOI18N
        cen12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cen12MouseClicked(evt);
            }
        });
        diente12.add(cen12);
        cen12.setBounds(24, 34, 22, 22);

        izq12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseIzq.png"))); // NOI18N
        izq12.setBorder(null);
        izq12.setBorderPainted(false);
        izq12.setContentAreaFilled(false);
        izq12.setMargin(new java.awt.Insets(1, 1, 1, 1));
        izq12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseIzqS.png"))); // NOI18N
        izq12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseIzqS.png"))); // NOI18N
        izq12.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseIzqS.png"))); // NOI18N
        izq12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izq12MouseClicked(evt);
            }
        });
        diente12.add(izq12);
        izq12.setBounds(10, 20, 15, 50);

        der12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseDer.png"))); // NOI18N
        der12.setBorder(null);
        der12.setBorderPainted(false);
        der12.setContentAreaFilled(false);
        der12.setMargin(new java.awt.Insets(1, 1, 1, 1));
        der12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseDerS.png"))); // NOI18N
        der12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseDerS.png"))); // NOI18N
        der12.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseDerS.png"))); // NOI18N
        der12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                der12MouseClicked(evt);
            }
        });
        diente12.add(der12);
        der12.setBounds(44, 20, 15, 50);

        inf12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseInf.png"))); // NOI18N
        inf12.setBorder(null);
        inf12.setBorderPainted(false);
        inf12.setContentAreaFilled(false);
        inf12.setMargin(new java.awt.Insets(1, 1, 1, 1));
        inf12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseInfS.png"))); // NOI18N
        inf12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseInfS.png"))); // NOI18N
        inf12.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/baseInfS.png"))); // NOI18N
        inf12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inf12MouseClicked(evt);
            }
        });
        diente12.add(inf12);
        inf12.setBounds(10, 54, 50, 15);

        per12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/perdida.png"))); // NOI18N
        per12.setBorderPainted(false);
        per12.setContentAreaFilled(false);
        diente12.add(per12);
        per12.setBounds(10, 20, 50, 50);

        getContentPane().add(diente12);
        diente12.setBounds(140, 30, 70, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariadaActionPerformed
        // TODO add your handling code here:
//       JOptionPane.showMessageDialog(this,evt.+"");
        
    }//GEN-LAST:event_cariadaActionPerformed

    private void der11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_der11MouseClicked
        // TODO add your handling code here:
          der11.setComponentPopupMenu(submenu);
          diente = "der11";
          submenu.show(der11,0,0);
        
    }//GEN-LAST:event_der11MouseClicked

    private void sup11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup11MouseClicked
        // TODO add your handling code here:
          sup11.setComponentPopupMenu(submenu);
          diente = "sup11";
          submenu.show(sup11,0,0);
    }//GEN-LAST:event_sup11MouseClicked

    private void cen11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cen11MouseClicked
        // TODO add your handling code here:
          cen11.setComponentPopupMenu(submenu);
          diente = "cen11";
          submenu.show(cen11,0,0);
    }//GEN-LAST:event_cen11MouseClicked

    private void inf11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inf11MouseClicked
        // TODO add your handling code here:
          inf11.setComponentPopupMenu(submenu);
          diente = "inf11";
          submenu.show(inf11,0,0);
    }//GEN-LAST:event_inf11MouseClicked

    private void izq11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izq11MouseClicked
        // TODO add your handling code here:
          izq11.setComponentPopupMenu(submenu);
          diente = "izq11";
          submenu.show(izq11,0,0);
    }//GEN-LAST:event_izq11MouseClicked

    private void sup12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sup12MouseClicked

    private void cen12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cen12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cen12MouseClicked

    private void izq12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izq12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_izq12MouseClicked

    private void der12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_der12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_der12MouseClicked

    private void inf12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inf12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inf12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cariada;
    private javax.swing.JButton cen11;
    private javax.swing.JButton cen12;
    private javax.swing.JButton der11;
    private javax.swing.JButton der12;
    private javax.swing.JPanel diente11;
    private javax.swing.JPanel diente12;
    private javax.swing.JButton inf11;
    private javax.swing.JButton inf12;
    private javax.swing.JButton izq11;
    private javax.swing.JButton izq12;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton per11;
    private javax.swing.JButton per12;
    private javax.swing.JPopupMenu submenu;
    private javax.swing.JButton sup11;
    private javax.swing.JButton sup12;
    // End of variables declaration//GEN-END:variables
}
