package peaje.formas;

import java.awt.Container;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.Copies;
import javax.print.attribute.standard.MediaPrintableArea;
import javax.print.attribute.standard.MediaSize;
import javax.print.attribute.standard.MediaSizeName;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPrintServiceExporter;
import net.sf.jasperreports.engine.export.JRPrintServiceExporterParameter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;
import hibernate.cargar.Administrador;
import hibernate.cargar.validaciones;
import hibernate.*;
import hibernate.cargar.WorkingDirectory;
import java.io.File;
import java.math.BigDecimal;
import java.util.Vector;
import sources.ClientesSource;
import sources.FacturaSource;
//import org.eclipse.persistence.internal.history.HistoricalDatabaseTable;

/**
 *
 * @author geovanny
 */
public class frmReportes extends javax.swing.JInternalFrame {

    /** Creates new form frmEmpresa */
    public boolean grabar = false;
    public boolean modificar = false;
    public List lista = null;
    public int posicion = 0;
    public int tamano = 0;
    private Container desktopContenedor;
    private Empresa empresaObj;
    Administrador adm;
    private String claveActual;
    private validaciones val;
    private principal principal;
 String separador = File.separatorChar+"";
    /** Creates new form frmProfesores */
    public frmReportes(principal lo, Administrador adm1) {
        this.principal = lo;
//          super(parent,modal);
        adm = adm1;
        llenarCombo();
        initComponents();
        this.setSize(615, 508);
        empresaObj = new Empresa();
        val = new validaciones();
         Date desde1 = new Date();
            Date hasta1 = new Date();
            desde1.setHours(06);
            desde1.setMinutes(00);
            desde1.setSeconds(00);
            hasta1.setHours(23);
            hasta1.setMinutes(59);
            hasta1.setSeconds(59);
            desdehora2.setDate(desde1);
            hastahora2.setDate(hasta1);
       
    }
//
//    public frmReportes(java.awt.Frame parent, boolean modal,principal lo) {
//        super(parent,modal);
//        this.desktopContenedor = lo.contenedor;
//        llenarCombo();
//        initComponents();
//        this.setSize(615, 508);
//        empresaObj = new Empresa();
//        adm = new Administrador();
//        val = new validaciones();
//        principal = lo;
//    }

    public void llenarCombo() {
       
        try {
            perfilesList = new ArrayList<Global>();
            perfilesList = adm.query("Select o from Global as o where o.grupo = 'PER'");
        } catch (Exception ex) {
            Logger.getLogger(frmReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

// <editor-fold defaultstate="collapsed" desc="PROPIEDADES">
    public String getClaveActual() {
        return claveActual;
    }

    public void setClaveActual(String claveActual) {
        this.claveActual = claveActual;
    }

    public Empresa getUsuarioObj() {
        return empresaObj;
    }

    public void setUsuarioObj(Empresa empresaObj) {
        this.empresaObj = empresaObj;
    }
    private List<Global> perfilesList = new ArrayList<Global>();

    public List<Global> getPerfilesList() {
        return perfilesList;
    }

    public void setPerfilesList(List<Global> perfilesList) {
        this.perfilesList = perfilesList;
    }

// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="FUNCIONES ACCIONES">
    // </editor-fold >
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        desde = new com.toedter.calendar.JDateChooser();
        hasta = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        hastahora2 = new com.toedter.calendar.JDateChooser();
        desdehora2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelReportes = new javax.swing.JPanel();

        setTitle("Reportes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultados.png"))); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/images_botones/fondoInicio.png")))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Catálogo de Reportes ..::..");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 0, 270, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Seleccione un reporte y presione ver ..::..");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 20, 250, 13);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("HORA:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 60, 60, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tickets por cobrar", "Tickets cobrados", "Puestos ocupados", "Facturas diarias", "Listado clientes", "Consolidado por mes", "Clientes mas frecuentes", " ", " " }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(80, 10, 300, 20);

        desde.setDate(new Date());
        desde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                desdeKeyPressed(evt);
            }
        });
        jPanel1.add(desde);
        desde.setBounds(80, 40, 130, 20);

        hasta.setDate(new Date());
        hasta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hastaKeyPressed(evt);
            }
        });
        jPanel1.add(hasta);
        hasta.setBounds(260, 40, 120, 20);

        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Reporte:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 60, 14);

        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("HORA:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 60, 14);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.gif"))); // NOI18N
        btnBuscar.setMnemonic('B');
        btnBuscar.setText("Ver");
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar);
        btnBuscar.setBounds(440, 10, 60, 50);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N
        btnSalir.setMnemonic('S');
        btnSalir.setText("Salir");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(510, 10, 60, 50);

        hastahora2.setDateFormatString("hh:mm:ss");
        hastahora2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hastahora2KeyPressed(evt);
            }
        });
        jPanel1.add(hastahora2);
        hastahora2.setBounds(260, 60, 100, 20);

        desdehora2.setDateFormatString("hh:mm:ss");
        desdehora2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                desdehora2KeyPressed(evt);
            }
        });
        jPanel1.add(desdehora2);
        desdehora2.setBounds(80, 60, 100, 20);

        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Desde:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 40, 60, 14);

        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Hasta:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 40, 60, 14);

        panelReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelReportes.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_formKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
                   principal.contenedor.requestFocus();
        this.setVisible(false);
        principal = null;
        empresaObj = null;
        System.gc();
}//GEN-LAST:event_btnSalirActionPerformed

    public void tickets(String dirreporte, String query, String titulo) {
        try {
            System.out.println("QUERY: "+query);
            JasperReport masterReport = (JasperReport) JRLoader.loadObject(dirreporte);
            Empresa emp = (Empresa) adm.querySimple("Select o from Empresa as o");

            List<Factura> fac = adm.query(query);
            ArrayList detalle = new ArrayList();
            for (Iterator<Factura> it = fac.iterator(); it.hasNext();) {
                Factura factura = it.next();
                detalle.add(factura);
            }
            FacturaSource ds = new FacturaSource(detalle);
            Map parametros = new HashMap();
            parametros.put("empresa", emp.getRazon());
            parametros.put("direccion", emp.getDireccion());
            parametros.put("telefono", emp.getTelefonos());
            parametros.put("titulo", titulo);
            parametros.put("parqueaderos", emp.getParqueaderos());
            if (jComboBox1.getSelectedIndex() == 2) {
                Object con = adm.querySimple("Select count(o) from Factura as o" +
                        " where  o.fechafin is null  ");
                Long val2 = (Long) con;
                System.out.println("" + con);
                parametros.put("ocupados", val2.intValue());
            }


            JasperPrint masterPrint = JasperFillManager.fillReport(masterReport, parametros, ds);
            JRViewer reporte = new JRViewer(masterPrint); //PARA VER EL REPORTE ANTES DE IMPRIMIR
            panelReportes.removeAll();
            reporte.repaint();
            reporte.setLocation(0, 0);
            reporte.setSize(723, 557);
            reporte.setVisible(true);
            panelReportes.add(reporte);
            panelReportes.repaint();
            this.repaint();
        } catch (Exception ex) {
            Logger.getLogger(frmTicket.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public void consolidado(String dirreporte, String query, String titulo) {
        try {
            System.out.println("QUERY: "+query);
            JasperReport masterReport = (JasperReport) JRLoader.loadObject(dirreporte);
            Empresa emp = (Empresa) adm.querySimple("Select o from Empresa as o");

            List fac = adm.queryNativo(query);
            ArrayList detalle = new ArrayList();
            for (Iterator it = fac.iterator(); it.hasNext();) {
                Factura fac01 = new Factura();
                 Vector factura =   (Vector) it.next();
                 Date fecha = (Date) factura.get(0);
                 BigDecimal valor = (BigDecimal) factura.get(1);
                 fac01.setFecha(fecha);
                 fac01.setTotal(valor);
                detalle.add(fac01);
            }
            FacturaSource ds = new FacturaSource(detalle);
            Map parametros = new HashMap();
            parametros.put("empresa", emp.getRazon());
            parametros.put("direccion", emp.getDireccion());
            parametros.put("telefono", emp.getTelefonos());
            parametros.put("titulo", titulo);
            parametros.put("parqueaderos", emp.getParqueaderos());
//            if (jComboBox1.getSelectedIndex() == 2) {
//                Object con = adm.querySimple("Select count(o) from Factura as o" +
//                        " where  o.fechafin is null  ");
//                Long val2 = (Long) con;
//                System.out.println("" + con);
//                parametros.put("ocupados", val2.intValue());
//            }


            JasperPrint masterPrint = JasperFillManager.fillReport(masterReport, parametros, ds);
            JRViewer reporte = new JRViewer(masterPrint); //PARA VER EL REPORTE ANTES DE IMPRIMIR
            panelReportes.removeAll();
            reporte.repaint();
            reporte.setLocation(0, 0);
            reporte.setSize(723, 557);
            reporte.setVisible(true);
            panelReportes.add(reporte);
            panelReportes.repaint();
            this.repaint();
        } catch (Exception ex) {
            Logger.getLogger(frmTicket.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void clientes(String dirreporte, String query, String titulo) {
        try {
            JasperReport masterReport = (JasperReport) JRLoader.loadObject(dirreporte);
            Empresa emp = (Empresa) adm.querySimple("Select o from Empresa as o");

            List<Clientes> fac = adm.query(query);
            ArrayList detalle = new ArrayList();
            for (Iterator<Clientes> it = fac.iterator(); it.hasNext();) {
                Clientes factura = it.next();
                detalle.add(factura);
            }
            ClientesSource ds = new ClientesSource(detalle);
            Map parametros = new HashMap();
            parametros.put("empresa", emp.getRazon());
            parametros.put("direccion", emp.getDireccion());
            parametros.put("telefono", emp.getTelefonos());
            parametros.put("titulo", titulo);
            parametros.put("parqueaderos", emp.getParqueaderos());
            if (jComboBox1.getSelectedIndex() == 2) {
                Object con = adm.querySimple("Select count(o) from Factura as o" +
                        " where  o.fechafin is null  ");
                Long val2 = (Long) con;
                System.out.println("" + con);
                parametros.put("ocupados", val2.intValue());
            }


            JasperPrint masterPrint = JasperFillManager.fillReport(masterReport, parametros, ds);
            JRViewer reporte = new JRViewer(masterPrint); //PARA VER EL REPORTE ANTES DE IMPRIMIR
            panelReportes.removeAll();
            reporte.repaint();
            reporte.setLocation(0, 0);
            reporte.setSize(723, 557);
            reporte.setVisible(true);
            panelReportes.add(reporte);
            panelReportes.repaint();
            this.repaint();
        } catch (Exception ex) {
            Logger.getLogger(frmTicket.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void pruebas() {
        String desde2 = (desde.getDate().getYear() + 1900) + "-" + (desde.getDate().getMonth() + 1) + "-" + (desde.getDate().getDate());
        String hasta2 = (hasta.getDate().getYear() + 1900) + "-" + (hasta.getDate().getMonth() + 1) + "-" + (hasta.getDate().getDate());

        String dirreporte = "", query = "", titulo = "";
        query = "Select o from Clientes as o" +
                "  ";
        dirreporte = "D:"+separador+"PROYECTOS"+separador+"peaje"+separador+"src"+separador+"reportes"+separador+"clientes.jasper";
        titulo = "Tickest por Cobrar";

        try {
            JasperReport masterReport = (JasperReport) JRLoader.loadObject(dirreporte);
            Empresa emp = (Empresa) adm.querySimple("Select o from Empresa as o");

            List<Clientes> fac = adm.query(query);
            ArrayList detalle = new ArrayList();
            for (Iterator<Clientes> it = fac.iterator(); it.hasNext();) {
                Clientes factura = it.next();
                detalle.add(factura);
            }
            ClientesSource ds = new ClientesSource(detalle);
            Map parametros = new HashMap();
            parametros.put("empresa", emp.getRazon());
            parametros.put("direccion", emp.getDireccion());
            parametros.put("telefono", emp.getTelefonos());
            parametros.put("titulo", titulo);
            parametros.put("parqueaderos", emp.getParqueaderos());
            if (jComboBox1.getSelectedIndex() == 2) {
                Object con = adm.querySimple("Select count(o) from Factura as o" +
                        " where  o.fechafin is null  ");
                Long val2 = (Long) con;
                System.out.println("" + con);
                parametros.put("ocupados", val2.intValue());
            }


            JasperPrint masterPrint = JasperFillManager.fillReport(masterReport, parametros, ds);


//PARA BUSCAR LAS IMPRESORAS INSTALADAS
//            PrintRequestAttributeSet printRequestAttributeSet = new HashPrintRequestAttributeSet();
//            PrinterJob comprobante = PrinterJob.getPrinterJob();
//            DocFlavor flavor = DocFlavor.SERVICE_FORMATTED.PRINTABLE;
//            PrintService impresoras[] = PrintServiceLookup.lookupPrintServices(null, printRequestAttributeSet);

//JasperPrint print = JasperFillManager.fillReport( this.class.getResource("/classpath/yourReport.jasper").getPath(), new HashMap(), new yourReportDataSource());
            PrinterJob job = PrinterJob.getPrinterJob();
            /* Create an array of PrintServices */
            PrintService[] services = PrintServiceLookup.lookupPrintServices(null, null);
            int selectedService = 0;
            /* Scan found services to see if anyone suits our needs */
            for (int i = 0; i < services.length; i++) {
                String nombre = services[i].getName().toUpperCase();
                if (nombre.contains("Office".toUpperCase())) {
                    /*If the service is named as what we are querying we select it */
                    selectedService = i;
                }
            }
            job.setPrintService(services[selectedService]);
            PrintRequestAttributeSet  printRequestAttributeSet = new HashPrintRequestAttributeSet();
            MediaSizeName mediaSizeName = MediaSize.findMedia(4, 4, MediaPrintableArea.INCH);
            printRequestAttributeSet.add(mediaSizeName);
            printRequestAttributeSet.add(new Copies(1));
            JRPrintServiceExporter exporter;
            exporter = new JRPrintServiceExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, masterPrint);
            /* We set the selected service and pass it as a paramenter */
            exporter.setParameter(JRPrintServiceExporterParameter.PRINT_SERVICE, services[selectedService]);
            exporter.setParameter(JRPrintServiceExporterParameter.PRINT_SERVICE_ATTRIBUTE_SET, services[selectedService].getAttributes());
            exporter.setParameter(JRPrintServiceExporterParameter.PRINT_REQUEST_ATTRIBUTE_SET, printRequestAttributeSet);
            exporter.setParameter(JRPrintServiceExporterParameter.DISPLAY_PAGE_DIALOG, Boolean.FALSE);
            exporter.setParameter(JRPrintServiceExporterParameter.DISPLAY_PRINT_DIALOG, Boolean.FALSE);
            exporter.exportReport();



//            JRViewer reporte = new JRViewer(masterPrint); //PARA VER EL REPORTE ANTES DE IMPRIMIR
//            panelReportes.removeAll();
//            reporte.repaint();
//            reporte.setLocation(0, 0);
//            reporte.setSize(723, 557);
//            reporte.setVisible(true);
//            panelReportes.add(reporte);
//            panelReportes.repaint();
//            this.repaint();
        } catch (Exception ex) {
            Logger.getLogger(frmTicket.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String query = "";
        String dirreporte = "";
       

        String desde2 = (desde.getDate().getYear() + 1900) + "-" + (desde.getDate().getMonth() + 1) + "-" + (desde.getDate().getDate());
        String hasta2 = (hasta.getDate().getYear() + 1900) + "-" + (hasta.getDate().getMonth() + 1) + "-" + (hasta.getDate().getDate());
//        String desde02 = (desde.getDate().getYear() + 1900) + "-" + (desde.getDate().getMonth() + 1) + "-" + (desde.getDate().getDate());
//        String hasta02 = (hasta.getDate().getYear() + 1900) + "-" + (hasta.getDate().getMonth() + 1) + "-" + (hasta.getDate().getDate());
            desde2 = desde2+" "+desdehora2.getDate().getHours()+":"+desdehora2.getDate().getMinutes()+":"+desdehora2.getDate().getSeconds();
            hasta2 = hasta2+" "+hastahora2.getDate().getHours()+":"+hastahora2.getDate().getMinutes()+":"+hastahora2.getDate().getSeconds();
        String titulo = "";
          WorkingDirectory w = new WorkingDirectory();
//            String query = "";
          String ubicacionDirectorio = w.get()+separador;
                if(ubicacionDirectorio.contains("build"))
                    ubicacionDirectorio = ubicacionDirectorio.replace(separador+"build", "");
        

        if (jComboBox1.getSelectedIndex() == 0) { //TICKEST POR COBRAR
            query = "Select o from Factura as o" +
                    " where o.fecha between '" + desde2 + "' and '" + hasta2 + "' and o.tarjetas is null "
                    + "and o.fechafin is null ";
            dirreporte = ubicacionDirectorio+"reportes"+separador+"ticketsporcobrar.jasper";
            titulo = "Tickest por Cobrar";
            tickets(dirreporte, query, titulo);
        } else if (jComboBox1.getSelectedIndex() == 1) {//TICKEST COBRADOS
            query = "Select o from Factura as o" +
                    " where o.fechafin between '" + desde2 + "' and '" + hasta2 + "' and o.tarjetas is null and o.fechafin is not null  ";
            dirreporte = ubicacionDirectorio+"reportes"+separador+"ticketscobrados.jasper";
            titulo = "Tickest Cobrados";
            tickets(dirreporte, query, titulo);

        } else if (jComboBox1.getSelectedIndex() == 2) {//PUESTO OCUPADOS
            query = "Select o from Factura as o" +
                    " where o.placa = 'xxxxxx..'";
            dirreporte = ubicacionDirectorio+"reportes"+separador+"ocupados.jasper";
            titulo = "Cupos Disponibles";
            tickets(dirreporte, query, titulo);

        } else if (jComboBox1.getSelectedIndex() == 3) {//FACTURADO
            query = "Select o from Factura as o" +
                    " where o.fechafin between '" + desde2 + "' and '" + hasta2 + "' and o.fechafin is not null ";
            dirreporte = ubicacionDirectorio+"reportes"+separador+"facturasdiarias.jasper";
            titulo = "Facturas ";
            tickets(dirreporte, query, titulo);

        } else if (jComboBox1.getSelectedIndex() == 4) {//LISTADO DE CLIENTES
            query = "Select o from Clientes as o where o.codigo > 1 order by o.nombres";
            dirreporte = ubicacionDirectorio+"reportes"+separador+"clientes.jasper";
            titulo = " ";
            clientes(dirreporte, query, titulo);

        } else if (jComboBox1.getSelectedIndex() == 5) {//CONSOLIDADO POR MES CLIENTES
            query = "Select date(o.fechafin),sum(o.total) from Factura as o" +
                    " where o.fechafin between '" + desde2 + "' and '" + hasta2 + "' "
                    + "  group by month(o.fechafin) ";
            dirreporte = ubicacionDirectorio+"reportes"+separador+"consolidado.jasper";
            titulo = " ";
            consolidado(dirreporte, query, titulo);

        } else if (jComboBox1.getSelectedIndex() == 6) {//CLIENTES MAS FRECUENTS CON TARJETAS
            query = "Select o from Clientes as o where o.codigo > 1 order by o.nombres";
            dirreporte = ubicacionDirectorio+"reportes"+separador+"clientes.jasper";
            titulo = " ";
            clientes(dirreporte, query, titulo);

        }
           principal.contenedor.requestFocus();

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex() == 3){
           
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        int cod = evt.getKeyCode();
        principal.tecla(cod);
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void desdeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desdeKeyPressed
        // TODO add your handling code here:
        principal.tecla(evt.getKeyCode());
    }//GEN-LAST:event_desdeKeyPressed

    private void hastaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hastaKeyPressed
        // TODO add your handling code here:
        principal.tecla(evt.getKeyCode());
    }//GEN-LAST:event_hastaKeyPressed

    private void desdehora2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desdehora2KeyPressed
        // TODO add your handling code here:
        principal.tecla(evt.getKeyCode());
    }//GEN-LAST:event_desdehora2KeyPressed

    private void hastahora2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hastahora2KeyPressed
        // TODO add your handling code here:
        principal.tecla(evt.getKeyCode());
    }//GEN-LAST:event_hastahora2KeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private com.toedter.calendar.JDateChooser desde;
    private com.toedter.calendar.JDateChooser desdehora2;
    private com.toedter.calendar.JDateChooser hasta;
    private com.toedter.calendar.JDateChooser hastahora2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelReportes;
    // End of variables declaration//GEN-END:variables
}
